name: Calculate The Embeddings

on:
  workflow_dispatch:

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@latest

    - name: Set up permissions for the script
      run: chmod +x ./kaggle/daily.sh

    - name: Execute the bash script
      run: ./kaggle/daily.sh
