name: Calculate The Embeddings

on:
  workflow_dispatch:
  schedule:
    - cron: '35 1 * * *'

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up permissions for the script
      run: chmod +x ./kaggle/daily.sh

    - name: Execute the bash script
      run: ./kaggle/daily.sh
